version: '3'

services:
  ans-background-job:
    build: .
    container_name: ans-background-job
    image: ans-background-job:latest
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ans-background-job:/usr/src/app/logs
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - NODE_PATH=/usr/src/app

volumes:
  ans-background-job: